-- 現場対応予定・行動管理システム Supabase セットアップ SQL
-- このスクリプトは Supabase の SQL Editor にコピー＆ペーストして実行してください。

-- 既存のテーブルがある場合は削除（注意：データは消去されます）
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS work_types CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS properties CASCADE;

-- 1. 物件マスタテーブルの作成
CREATE TABLE properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_number TEXT NOT NULL,
  property_name TEXT NOT NULL,
  address TEXT,
  box_count INTEGER,
  model_type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_properties_unit_number ON properties(unit_number);
CREATE INDEX idx_properties_property_name ON properties(property_name);

-- 2. スタッフ（対応者）テーブルの作成
CREATE TABLE staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  default_course TEXT,
  is_active INTEGER DEFAULT 1,
  role TEXT DEFAULT 'user',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. 予定項目（種別）マスタテーブルの作成
CREATE TABLE work_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  is_internal INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. スケジュール（予定）テーブルの作成
CREATE TABLE schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT NOT NULL, -- 'draft' (仮), 'confirmed' (確定), 'cancelled' (キャンセル)
  division TEXT, -- 区分
  type TEXT, -- タイプ
  box TEXT, -- BOX
  unit_number TEXT, -- 号機
  property_name TEXT NOT NULL, -- 物件名
  work_type TEXT, -- 種別 (フリー、定期、工事、保守、障害対応など)
  description TEXT, -- 作業内容
  target_time TEXT, -- 時間
  date TEXT NOT NULL, -- YYYY-MM-DD
  staff_id BIGINT REFERENCES staff(id) ON DELETE SET NULL, -- 対応者
  staff_name TEXT, -- 対応者名（非正規化/表示用）
  area TEXT, -- エリア
  prefecture TEXT, -- 県別
  transport TEXT, -- 移動
  co_worker TEXT, -- 同行者
  request_number TEXT, -- 依頼番号
  time_limit TEXT, -- TIME
  course TEXT, -- コース
  result TEXT, -- 結果 (空欄 または '完了' など)
  started_at TEXT, -- 開始時刻 (HH:MM)
  completed_at TEXT, -- 完了時刻 (HH:MM)
  notes TEXT, -- 備考
  report_notes TEXT, -- 対応報告メモ
  disorder_type TEXT, -- 障害区分
  level TEXT, -- level
  level_3 TEXT, -- level 3
  sort_order INTEGER DEFAULT 0,
  is_transferred INTEGER DEFAULT 0, -- 行動予定表へ移行済みフラグ
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_schedules_date ON schedules(date);
CREATE INDEX idx_schedules_staff_id ON schedules(staff_id);

-- 5. 操作履歴テーブルの作成
CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT,
  action TEXT NOT NULL,
  changed_by TEXT NOT NULL,
  property_name TEXT,
  details TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_logs_timestamp ON audit_logs(timestamp);
CREATE INDEX idx_audit_logs_schedule_id ON audit_logs(schedule_id);


-- ==========================================
-- 初期データの投入
-- ==========================================

-- 1. 予定種別マスタデータのインサート
INSERT INTO work_types (name, is_internal, sort_order) VALUES
('休暇', 1, 1),
('ミーティング', 1, 2),
('会議', 1, 3),
('研修', 1, 4),
('社内', 1, 5),
('面談', 1, 6),
('障害', 0, 1),
('工事', 0, 2),
('定期', 0, 3),
('保守', 0, 4),
('依頼有/非認可', 0, 5),
('フリー', 0, 6);

-- 2. スタッフデータのインサート
INSERT INTO staff (name, email, default_course, role) VALUES
('平本', 'hiramoto@example.com', '1', 'user'),
('築地', 'tsukiji@example.com', '2', 'user'),
('藤井', 'fujii@example.com', '3', 'user'),
('神崎', 'kanzaki@example.com', '4', 'user'),
('原',   'hara@example.com', '5', 'user'),
('土橋', 'dobashi@example.com', '6', 'user'),
('藤田', 'fujita@example.com', '7', 'user'),
('佐藤', 'sato@example.com', '8', 'admin'),
('吉沼', 'yoshinuma@example.com', '9', 'user'),
('小山', 'koyama@example.com', '10', 'user'),
('高橋', 'takahashi@example.com', '11', 'user'),
('畦崎', 'unezaki@example.com', '12', 'user'),
('フーギー', 'foogy@example.com', '13', 'user'),
('松下', 'matsushita@example.com', '14', 'user'),
('淺沼', 'asanuma@example.com', '15', 'user'),
('山内', 'yamauchi@example.com', '16', 'user'),
('中川', 'nakagawa@example.com', '17', 'user'),
('阿部', 'abe@example.com', '18', 'user'),
('藤崎', 'fujisaki@example.com', '19', 'user'),
('本間', 'homma@example.com', '20', 'user'),
('丸山', 'maruyama@example.com', '21', 'user'),
('清水', 'shimizu@example.com', '22', 'user'),
('塙',   'hanawa@example.com', '23', 'user'),
('伊比', 'ibi@example.com', '24', 'user'),
('石山', 'ishiyama@example.com', '25', 'user'),
('平井', 'hirai@example.com', '26', 'user'),
('FE武田', 'takeda@example.com', '90', 'user'),
('SF濱田', 'hamada@example.com', '91', 'user'),
('FR岡崎', 'okazaki@example.com', '92', 'user'),
('FR土屋', 'tsuchiya@example.com', '93', 'user'),
('FR宮本', 'miyamoto@example.com', '94', 'user'),
('FR金谷', 'kanaya@example.com', '95', 'user');

-- 3. デモ用の初期予定データ
INSERT INTO schedules (status, division, type, box, unit_number, property_name, work_type, description, target_time, date, staff_id, staff_name, area, prefecture, transport, co_worker, request_number, time_limit, course, result, completed_at, sort_order, is_transferred)
VALUES 
('confirmed', 'FTS', '', '22420', '', 'フランセ', '障害', '定期メンテナンス完了報告。全ボックス。署名/居住者ともボックス内の消防用注意シールが一部剥がれており', '', '2026-06-12', (SELECT id FROM staff WHERE name = '原' LIMIT 1), '原', '', '', '', '', '12604010057', '', '5', '完了', '10:30', 0, 0),
('confirmed', 'FTS', '', '', '2902', 'エル・コモド葛西', '依頼有/非認可', '＜2次対応＞ 通信モデム＋CPUボード基板', '09:00', '2026-06-12', (SELECT id FROM staff WHERE name = '原' LIMIT 1), '原', '', '', '', '', '1260520224', '', '5', '', NULL, 0, 0);

-- 4. 物件マスタのダミーデータ（10,000件）をPL/pgSQLで生成して投入
CREATE OR REPLACE FUNCTION generate_dummy_properties() RETURNS void AS $$
DECLARE
  prefectures text[] := ARRAY['東京', '神奈川', '埼玉', '千葉', '長野'];
  cities text[] := ARRAY['世田谷区', '川崎市宮前区', 'さいたま市大宮区', '船橋市', '松本市'];
  models text[] := ARRAY['Type-A', 'Type-B', 'Type-C', 'Type-D'];
  names text[] := ARRAY['エル・コモド', 'ドレッセ', 'サンライズ', 'グリーンヒル', 'メゾン・ド', 'パークハイツ', 'コンフォート', 'グランディール', 'シャトー', 'ビューハイツ'];
  suffixes text[] := ARRAY['葛西', '下馬', '宮前平', '大宮', '松本', '船橋', '世田谷', '渋谷', '新宿', '横浜'];
  i integer;
  unitNum text;
  nameBase text;
  nameSuffix text;
  propName text;
  pref text;
  city text;
  addr text;
  boxCount integer;
  modelType text;
BEGIN
  FOR i IN 1..10000 LOOP
    unitNum := (100000 + i)::text;
    nameBase := names[mod(i, array_length(names, 1)) + 1];
    nameSuffix := suffixes[mod((i + i / array_length(names, 1)), array_length(suffixes, 1)) + 1];
    propName := nameBase || nameSuffix || '第' || ceil(i / 100.0)::text || '棟';
    
    pref := prefectures[mod(i, array_length(prefectures, 1)) + 1];
    city := cities[mod(i, array_length(cities, 1)) + 1];
    addr := pref || city || ' ' || mod(i, 10)::text || '-' || mod(i, 3)::text;
    
    boxCount := 4 + mod(i, 16);
    modelType := models[mod(i, array_length(models, 1)) + 1];

    INSERT INTO properties (unit_number, property_name, address, box_count, model_type)
    VALUES (unitNum, propName, addr, boxCount, modelType);
  END LOOP;
END;
$$ LANGUAGE plpgsql;

-- 生成ファンクションを実行してダミーデータを生成
SELECT generate_dummy_properties();

-- 使い終わったファンクションは削除
DROP FUNCTION generate_dummy_properties();
